### ISSUE TITLE
Comments on tasks

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-client#10]
- [x] In a task detail view, all comments are displayed below
- [x] display all properties of other comments
- [x] Option to add comment (like youtube)
- [x] input validation
- [x] api request (get and submit, auth)
- [x] error display (all rest specs, validation)
- [x] input field
- [x] update on adding new comment (i.e., fetch again all comments)

**Comment by Monti934** [comment]
@B1s9l need live updates via pusher, everything else should work

**Comment by B1s9l** [comment]
See commit 3d3d785 for changes to this issue (Pusher api for sync).
