### ISSUE TITLE
Login form UI

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-client#3]
- [x] validation of input
- [x] error visualization (not alert) of validation fail, request response
- [x] api request
- [x] send hashed password (talk with backend for correct hashing)
- [x] On sucessfull, route to after login
- [x] Documentation

**Comment by B1s9l** [comment]
- [] change index.html with group name

**Comment by B1s9l** [comment]
See commit 2489bb9 for changes related to this issue.
