### ISSUE TITLE
Login: Logged in user overview

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-client#4]
- [x] UI after login go to team overview
- [x] groups available in a grid (add new group in sopra-fs24-group07/sopra-fs24-group-07-server#5)
- [x] correct user image in user toolbar (moved to sopra-fs24-group07/sopra-fs24-group-07-client#29)

**Comment by 5v3nn** [comment]
@B1s9l if done, set to done and close issue

**Comment by 5v3nn** [comment]
yes was done and

**Comment by B1s9l** [comment]
See commit 71aee3d for changes to this issue.
