### ISSUE TITLE
Team Dashboard UI

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-client#6]
- [x] Dashboard with widgets (bot no functionality yet)
- [x] display all users (api request for that, auth)
- [x] display all tasks (api with auth) belongs to this issue: sopra-fs24-group07/sopra-fs24-group-07-client/issues/35
- [x] display time spent to far (api with auth)
- [x] make sure functionallity for accessign user profile still works

**Comment by Monti934** [comment]
Fix: time goal input is in foreground when userprofile is opened

**Comment by B1s9l** [comment]
See commit 7106aca for changes to this issue.
